# Generated by Django 4.2.7 on 2023-11-23 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interview', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='interview',
            name='interview_time_slot',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='interview',
            name='interview_date',
            field=models.CharField(max_length=20),
        ),
    ]
