# Generated by Django 4.2.7 on 2023-11-23 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interview', '0002_interview_interview_time_slot_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interview',
            name='interview_time_slot',
            field=models.CharField(default='NULL', max_length=20),
        ),
    ]
