# Generated by Django 4.2.7 on 2024-01-26 18:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('registration', '0001_initial'),
        ('interview', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InterviewerAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.CharField(max_length=50)),
                ('end_time', models.CharField(max_length=50)),
                ('interview_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='interview.interview')),
                ('interviewer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registration.interviewerdetails')),
            ],
            options={
                'unique_together': {('interviewer_id', 'interview_code', 'start_time', 'end_time')},
            },
        ),
        migrations.CreateModel(
            name='CandidateAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.CharField(max_length=50)),
                ('end_time', models.CharField(max_length=50)),
                ('candidate_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registration.candidatedetails')),
                ('interview_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='interview.interview')),
            ],
            options={
                'unique_together': {('candidate_id', 'interview_code', 'start_time', 'end_time')},
            },
        ),
    ]
