# Generated by Django 4.2.7 on 2023-11-24 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0001_initial'),
        ('interview', '0001_initial'),
        ('availability_pro', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='candidateavailability',
            unique_together={('candidate_id', 'interview_code', 'start_time', 'end_time')},
        ),
        migrations.AlterUniqueTogether(
            name='intervieweravailability',
            unique_together={('interviewer_id', 'interview_code', 'start_time', 'end_time')},
        ),
    ]
