# Generated by Django 4.2.7 on 2023-11-23 21:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('availability_pro', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='candidateavailability',
            old_name='interview_date',
            new_name='interview_code',
        ),
    ]
