# Generated by Django 4.2.7 on 2023-11-23 21:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('availability_pro', '0002_rename_interview_date_candidateavailability_interview_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='intervieweravailability',
            old_name='interview_date',
            new_name='interview_code',
        ),
    ]
